package handlers

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"log"
	"net/http"
	"talent_glimpse/common/response"
	"talent_glimpse/common/typ"
)

func CreateRecruitmentInfo(ctx *gin.Context) {
	var req typ.CreateRecruitmentInfoReq
	if err := ctx.ShouldBindJSON(&req); err != nil {
		log.Println(fmt.Errorf("[CreateRecruitmentInfo] param bid error: %v", err))
		ctx.JSON(http.StatusBadRequest, &response.T{
			MetaData: &response.MetaData{
				Code: http.StatusBadRequest,
				Msg:  "An error message generated by ShouldBindJson: " + err.Error(),
			},
		})
		return
	}

}
